### ISSUE TITLE
ETA

### ISSUE THREAD

**Issue by sberryman** [zju3dv/GIFT#1]
Excellent paper, looking forward to testing it on 3D reconstruction using drone imagery. Any ETA on publishing the code and ideally pre-trained models or at least the training code?

Thanks!

**Comment by liuyuan-pal** [comment]
Thanks for your interest in our paper! We plan to release the code at the end of this month.
We will release training/testing codes and pretrained models.

**Comment by sberryman** [comment]
Thanks for the update!

**Comment by liuyuan-pal** [comment]
I have released codes today.
