### ISSUE TITLE
Dense correspondence demo?

### ISSUE THREAD

**Issue by YamamotoSayaka** [zju3dv/GIFT#10]
Hi, many thanks for opening this code! 
Can you provide a demo for dense correspondence estimation as in the homepage?

**Comment by liuyuan-pal** [comment]
Hi, sorry for the late reply.
the dense correspondence here is to use all coordinates on the image plane as keypoints (the "pts" parameter in the following).
https://github.com/zju3dv/GIFT/blob/5b601c721c1e2864de957b0b8c90c020acf5930e/network/wrapper.py#L200

**Comment by YamamotoSayaka** [comment]
Many thanks!
