### ISSUE TITLE
About the implementation of Group CNNs

### ISSUE THREAD

**Issue by JUGGHM** [zju3dv/GIFT#12]
Hi, Yuan Liu:
    Thanks for opening source! It is a novel and interesting application utilizing group cnns.
    Actually I don't clarify how the rotation gcnn and scale gcnn are implemented in:
    [class RotationalConv2D(nn.Conv2d):](https://github.com/zju3dv/GIFT/blob/5b601c721c1e2864de957b0b8c90c020acf5930e/network/operator.py#L20)
    [class GREBilinearPoolPaddingDeepMoreScale](https://github.com/zju3dv/GIFT/blob/5b601c721c1e2864de957b0b8c90c020acf5930e/network/embedder.py#L169)
    They seems actually the same as vanilla convolutions, don't they? Or I must be misunderstanding it. Would you like to help me out?

**Comment by liuyuan-pal** [comment]
Hi, thanks for your interest!

The key difference is the circular padding along the rotation direction because the rotation group is cyclic. Other than that, the convolution is the same as vanilla convolution.

https://github.com/zju3dv/GIFT/blob/5b601c721c1e2864de957b0b8c90c020acf5930e/network/operator.py#L49

**Comment by JUGGHM** [comment]
> Hi, thanks for your interest!
> 
> The key difference is the circular padding along the rotation direction because the rotation group is cyclic. Other than that, the convolution is the same as vanilla convolution.
> 
> https://github.com/zju3dv/GIFT/blob/5b601c721c1e2864de957b0b8c90c020acf5930e/network/operator.py#L49

Thanks for your answer. Now I wonder if my following understanding about GIFT is right:
The group equivalence are mainly obtained by sub-group transformations, not group equivalent CNNs proposed by Cohen?

**Comment by liuyuan-pal** [comment]
The group convolution is the same as proposed in Group CNNs by Cohen. The difference is that we only consider the scale-rotation group while Group CNNs consider the translation-rotation group.

**Comment by JUGGHM** [comment]
> The group convolution is the same as proposed in Group CNNs by Cohen. The difference is that we only consider the scale-rotation group while Group CNNs consider the translation-rotation group.

Thanks a lot! Now I see that actually via vanilla conv group cnns are implemented. It is just that the common width and height dimension are now representing the groups!
