### ISSUE TITLE
What's the  cameraMatrix related to ?

### ISSUE THREAD

**Issue by jingmouren** [zju3dv/GIFT#4]
It's related to the training data set,  so when matching other images, using the same matrix as the example.
Or related to the testing time, so it can only be used to matching images that knows the matrix and must be provided by the user?

**Comment by liuyuan-pal** [comment]
Hi~I don't know exactly which "matrix" you refer to.

**Comment by jingmouren** [comment]
I mean the K0 and K1 camera matrix used in  computing the inline matched point and the corresponding angle in the notebook.

**Comment by liuyuan-pal** [comment]
They are the intrinsic matrices of two images which are used in the computation of the pose. Matching doesn't require these two matrices.
