### ISSUE TITLE
memory problem

### ISSUE THREAD

**Issue by jingmouren** [zju3dv/GIFT#5]
I try to match template image to other images in a folder in a loop, the match function is from the demo notebook.
The first and second try passed, bu no free the GPU memroy and the third match try failed. Which block consumes the GPU memory and how to manuly free the memory?

**Comment by liuyuan-pal** [comment]
The GPU memory is managed by Pytorch automatically, so it should be released after every forward pass. Maybe, too many points are detected or the input image is too large. The current version does consume a lot of GPU memory when computing feature maps on every warp image.

**Comment by liuyuan-pal** [comment]
Actually, there is a solution that we can use features extracted on patches of different scales and orientations as the input to the Group CNNs, which would avoid computing a whole feature map of a warped image. This may reduce memory consumption and may also improve the performance but is less time-efficient.
