### ISSUE TITLE
用到的cuda的extension有cpu版的参考实现吗？

### ISSUE THREAD

**Issue by jingmouren** [zju3dv/GIFT#6]

**Comment by liuyuan-pal** [comment]
你好，这里只是把模型放到了GPU上运行，如果将code中的.cuda()都去掉，那么模型就是运行在CPU上了。

**Comment by jingmouren** [comment]
主要是说的cpu参考
hard_mining build_ext
和 utils/extend_utils build_extend_utils_cffi.py

**Comment by liuyuan-pal** [comment]
hard example mining是训练过程来找hard example的，CPU上训练太慢了所以不建议使用。
extend_utils这里面基本上只是一个GPU版本的nearest neighborhood matcher，你可以考虑用opencv的matcher或者pyflann的matcher替代，他们都是CPU上的。
